//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingId { get; set; }
        public string BookingRestaurant { get; set; }
        public string SeatsNumber { get; set; }
        public string Requirements { get; set; }
        public string BookingDate { get; set; }
        public string UserId { get; set; }
        public string Date { get; set; }
    }
}
