//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurants
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Signaturedish { get; set; }
        public string ReceptionCapacity { get; set; }
        public string PerCapitaConsumption { get; set; }
        public string OpeningHours { get; set; }
        public string Date { get; set; }
    }
}
