//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System;
    using System.Collections;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantBookingModelContainer : DbContext
    {
        public RestaurantBookingModelContainer()
            : base("name=RestaurantBookingModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Restaurants> RestaurantsSet { get; set; }
        public virtual DbSet<Booking> BookingSet { get; set; }
        public IEnumerable AspNetUsers { get; internal set; }
    }
}
